#bash/bin
./expert_system test/double_implies.txt
./expert_system test/ambiguos_test.txt		
./expert_system test/mix2.txt
./expert_system test/and.txt				
./expert_system test/not.txt
./expert_system test/complex_contradiction.txt	
./expert_system test/or.txt
./expert_system test/contradiction.txt		
./expert_system test/parenthesis.txt
./expert_system test/double_implies.txt		
./expert_system test/sample.txt
./expert_system test/mix.txt				
./expert_system test/xor.txt
./expert_system test/test.txt
./expert_system test/test1.txt
./expert_system test/test2.txt
./expert_system test/test3.txt
./expert_system test/test4.txt
./expert_system test/test5.txt
./expert_system test/test6.txt